-- seed_curation.sql — GENERATED by scripts/gen_seed.ts from
-- curation_overrides.jsonl. Do not edit by hand; edit the overrides
-- (with reasons) and regenerate (deno task gen-seed).
--
-- Runs LAST: applies the audited curation overrides (plan 0013), fills
-- the density tail from the FAO/INFOODS fallback, then refreshes the
-- template vocab's materialized allowed_units now that every density
-- source has run.
--
-- Density fallback dataset: FAO/INFOODS Density Database v2.0 (2012)
-- (see seed/fao_density.jsonl for the source URL + sha256, and
--  seed/fao_density_links.jsonl for the reviewed mapping).

begin;

-- nutritional yeast: no FDC food (yeast extract spread is not nooch); Bragg's label per 16 g serving, scaled to 100 g
update ingredient set
  macros = '{"kcal":375,"protein":50,"fat":3.1,"carb":31.3,"fiber":18.8}'::jsonb,
  source = 'label:Bragg nutritional yeast',
  status = 'complete'
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'nutritional yeast';

-- dijon mustard: no FDC dijon (only prepared yellow); Maille's EU label prints per-100 g directly
update ingredient set
  macros = '{"kcal":161,"protein":7.5,"fat":12,"carb":3.5}'::jsonb,
  source = 'label:Maille Dijon Originale',
  status = 'complete'
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'dijon mustard';

-- rice vinegar: no FDC rice vinegar; unseasoned brewed rice vinegar labels round to zero per tbsp — ~18 kcal/100 ml from residual sugars is the typical analytic value
update ingredient set
  macros = '{"kcal":18,"protein":0,"fat":0,"carb":1.5}'::jsonb,
  source = 'label:typical unseasoned rice vinegar',
  status = 'complete'
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'rice vinegar';

-- farro: no FDC farro (emmer); label per 47 g serving, scaled to 100 g
update ingredient set
  macros = '{"kcal":319,"protein":10.6,"fat":2.1,"carb":68.1,"fiber":8.5}'::jsonb,
  source = 'label:Bob''s Red Mill organic farro',
  status = 'complete'
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'farro';

-- vegan mayonnaise: no FDC vegan mayo (imitation soybean mayo is a low-fat product, not this); label per 14 g serving, scaled to 100 g
update ingredient set
  macros = '{"kcal":643,"protein":0,"fat":71.4,"carb":7.1}'::jsonb,
  source = 'label:Hellmann''s vegan mayo',
  status = 'complete'
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'vegan mayonnaise';

-- sprouted multigrain bread: FDC 171850 prints fat 0 for a whole-grain seeded bread — impossible; the category-defining sprouted loaf's label (per 34 g slice) scaled to 100 g
update ingredient set
  macros = '{"kcal":235,"protein":11.8,"fat":1.5,"carb":44.1,"fiber":8.8}'::jsonb,
  source = 'label:Food for Life Ezekiel 4:9',
  status = 'complete'
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'sprouted multigrain bread';

-- black bean canned: round-2 ruling (a): own FDC food is with-liquid can contents while the can measure is pinto's drained solids; borrow pinto's drained basis for coherence
update ingredient set
  macros = '{"kcal":114,"protein":6.99,"fat":0.9,"carb":20.22,"fiber":5.5}'::jsonb,
  source = 'usda_fdc:174286 — borrowed (pinto, drained solids)',
  status = 'complete'
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'black bean canned';

-- black eyed pea canned: round-2 ruling (a): own FDC food is with-liquid can contents while the can measure is pinto's drained solids; borrow pinto's drained basis for coherence
update ingredient set
  macros = '{"kcal":114,"protein":6.99,"fat":0.9,"carb":20.22,"fiber":5.5}'::jsonb,
  source = 'usda_fdc:174286 — borrowed (pinto, drained solids)',
  status = 'complete'
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'black eyed pea canned';

-- cannellini bean canned: round-2 ruling (a): own FDC food is with-liquid can contents while the can measure is pinto's drained solids; borrow pinto's drained basis for coherence
update ingredient set
  macros = '{"kcal":114,"protein":6.99,"fat":0.9,"carb":20.22,"fiber":5.5}'::jsonb,
  source = 'usda_fdc:174286 — borrowed (pinto, drained solids)',
  status = 'complete'
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cannellini bean canned';

-- great northern bean canned: round-2 ruling (a): own FDC food is with-liquid can contents while the can measure is pinto's drained solids; borrow pinto's drained basis for coherence
update ingredient set
  macros = '{"kcal":114,"protein":6.99,"fat":0.9,"carb":20.22,"fiber":5.5}'::jsonb,
  source = 'usda_fdc:174286 — borrowed (pinto, drained solids)',
  status = 'complete'
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'great northern bean canned';

-- navy bean canned: round-2 ruling (a): own FDC food is with-liquid can contents while the can measure is pinto's drained solids; borrow pinto's drained basis for coherence
update ingredient set
  macros = '{"kcal":114,"protein":6.99,"fat":0.9,"carb":20.22,"fiber":5.5}'::jsonb,
  source = 'usda_fdc:174286 — borrowed (pinto, drained solids)',
  status = 'complete'
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'navy bean canned';

-- banana: the ranked pick landed on FDC's mashed cup (225 g -> 0.951); sliced (150 g/cup -> 0.634) is what a volume of banana means in a recipe
update ingredient set density_g_per_ml = 0.634
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'banana';

-- rolled oat: FDC 169705's 156 g cup describes steel-cut/whole oats; rolled-oat labels print 40 g per 1/2 cup (~81 g/cup -> 0.34) and Steel-Cut Oats keeps the FDC value
update ingredient set density_g_per_ml = 0.34
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'rolled oat';

-- kosher salt: prefill copied table salt (1.234) but kosher is flaked: Diamond Crystal ~2.8 g/tsp (0.57), Morton ~4.8 g/tsp (0.97) — 0.7 is the defensible middle; per-brand truth belongs to the user's own edit
update ingredient set density_g_per_ml = 0.7
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'kosher salt';

-- flaky salt: prefill copied table salt (1.234); Maldon-style pyramid flakes run ~2.7 g/tsp (label serving) -> ~0.55
update ingredient set density_g_per_ml = 0.55
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'flaky salt';

-- agave: FDC 170277's own tsp row (6.9 g -> 1.40) is right; the ranked pick took the 1/4-cup row (55 g -> 0.93) which is physically impossible for a syrup
update ingredient set density_g_per_ml = 1.39
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'agave';

-- almond milk: FDC 174832's cup portion overweighs (1.107); almond milk is nearly all water — labels say 240 ml ~= 245 g (1.01)
update ingredient set density_g_per_ml = 1.01
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'almond milk';

-- sriracha: FDC 171186's 6.5 g tsp (1.32) overweighs; Huy Fong's label tsp is 5 g (~1.0) — 1.05 for a dense puree
update ingredient set density_g_per_ml = 1.05
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'sriracha';

-- flaxseed meal: prefill value (0.71) is whole flaxseed; ground meal is fluffier — labels (Bob's Red Mill/Spectrum) say 2 tbsp ~= 13-14 g -> 0.47
update ingredient set density_g_per_ml = 0.47
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'flaxseed meal';

-- spelt flour: prefill value (0.736) is the whole spelt grain (FDC 169745); milled spelt flour labels say 1/4 cup = 30 g -> 0.51
update ingredient set density_g_per_ml = 0.51
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'spelt flour';

-- vanilla paste: prefill copied vanilla extract (0.879, alcohol-based); paste is a thick sugar syrup — Nielsen-Massey label tsp ~6 g -> ~1.2
update ingredient set density_g_per_ml = 1.2
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'vanilla paste';

-- hummus: FDC 321358's cup row lands 1.146 which overweighs a whipped spread; label tbsp ~15-16 g -> ~1.04
update ingredient set density_g_per_ml = 1.04
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'hummus';

-- panko: prefill copies standard grated crumbs (108 g/cup -> 0.456); panko flakes are far airier — labels (Kikkoman) say 1/2 cup = 30 g -> 0.25
update ingredient set density_g_per_ml = 0.25
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'panko';

-- wheat flour whole: Foundation 790085 carries no volume portion; whole-wheat flour labels say 1/4 cup = 30 g (~120 g/cup -> 0.51)
update ingredient set density_g_per_ml = 0.51
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'wheat flour whole';

-- white rice flour: Foundation 790214 carries no volume portion; SR rice flour's cup is 158 g -> 0.67
update ingredient set density_g_per_ml = 0.67
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'white rice flour';

-- almond flour: Foundation 2261420 carries no volume portion; labels (King Arthur ~96 g/cup, Blue Diamond 28 g per 1/4 cup) -> ~0.41
update ingredient set density_g_per_ml = 0.41
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'almond flour';

-- cashew: FDC 170162 has only mass portions; a cup of whole raw cashews is ~137 g -> 0.58
update ingredient set density_g_per_ml = 0.58
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cashew';

-- chia seed: FDC 170554 has only oz portions; labels say 2 tbsp ~= 24 g -> 0.81
update ingredient set density_g_per_ml = 0.81
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'chia seed';

-- nutritional yeast: no FDC food; flake-size varies wildly by brand (Bragg 2 tbsp = 16 g -> 0.54, Bob's large flake 1/4 cup = 15 g -> 0.25) — 0.4 is the middle of the honest range
update ingredient set density_g_per_ml = 0.4
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'nutritional yeast';

-- kale: FDC 168421 lacks a cup row; a cup of chopped raw kale is ~21 g -> 0.089
update ingredient set density_g_per_ml = 0.089
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'kale';

-- arugula: FDC 169387's own half-cup leaf row is 10 g -> 0.085 (excluded by the ranked pick's sanity floor)
update ingredient set density_g_per_ml = 0.085
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'arugula';

-- cilantro: FDC 169997's 1/4-cup row is 4 g -> 0.068 (below the derivation's 0.1 sanity floor, but leafy herbs genuinely are this light)
update ingredient set density_g_per_ml = 0.068
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cilantro';

-- dill: FDC 172233's sprig-cup ~9 g -> 0.038; feathery fresh dill really is near-weightless per cup
update ingredient set density_g_per_ml = 0.038
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'dill';

-- ketchup: Foundation 747693 carries no volume portion; SR ketchup tbsp is 17 g -> 1.14
update ingredient set density_g_per_ml = 1.14
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'ketchup';

-- oat milk: Foundation 2257046 carries no volume portion; oat milk is nearly all water — label 240 ml ~= 243 g -> 1.01
update ingredient set density_g_per_ml = 1.01
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'oat milk';

-- plant milk: generic milk-alternative slot: every common plant milk (oat/soy/almond) sits at ~1.01
update ingredient set density_g_per_ml = 1.01
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'plant milk';

-- rice vinegar: no FDC food; a 4-5% acetic solution is water-like — FDC's other vinegars sit 1.01 (typical)
update ingredient set density_g_per_ml = 1
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'rice vinegar';

-- sherry vinegar: no FDC food; wine vinegars (FDC red wine vinegar) sit at 1.01
update ingredient set density_g_per_ml = 1.01
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'sherry vinegar';

-- ume plum vinegar: no FDC food; a salted plum brine, slightly denser than plain vinegar (typical)
update ingredient set density_g_per_ml = 1.02
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'ume plum vinegar';

-- dijon mustard: no FDC dijon; label tsp is 5 g -> ~1.0-1.05 (prepared yellow mustard's FDC density is 0.99; dijon is slightly denser)
update ingredient set density_g_per_ml = 1.05
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'dijon mustard';

-- vegan mayonnaise: no FDC food; label (Hellmann's vegan) tbsp = 14 g -> 0.95, matching dairy mayo
update ingredient set density_g_per_ml = 0.96
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'vegan mayonnaise';

-- mini pretzel: FDC 167555 has no cup row; a cup of mini twists is ~55 g by label serving math (20 minis = 28 g) -> 0.23
update ingredient set density_g_per_ml = 0.23
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'mini pretzel';

-- chex cereal: audit suggested 0.25 but that is Wheat Chex only; snack-mix recipes overwhelmingly use Rice/Corn Chex whose labels say 27-31 g per cup -> 0.13 (recorded disagreement)
update ingredient set density_g_per_ml = 0.13
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'chex cereal';

-- orange juice: matches the new FDC 169098 link (cup 248 g); kept explicit so the R1 invariant documents the value with the fills
update ingredient set density_g_per_ml = 1.048
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'orange juice';

-- farro: no FDC food; label (Bob's Red Mill) 1/4 cup = 47 g -> ~188 g/cup -> 0.79
update ingredient set density_g_per_ml = 0.79
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'farro';

-- black rice: no FDC food; dry rice cups run ~185 g (typical, matches white/brown rice family)
update ingredient set density_g_per_ml = 0.78
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'black rice';

-- red rice: no FDC food; dry rice cups run ~185 g (typical, matches white/brown rice family)
update ingredient set density_g_per_ml = 0.78
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'red rice';

-- coconut whip: no FDC food; whipped toppings are mostly air — label (So Delicious CocoWhip) 2 tbsp = 9 g -> 0.3
update ingredient set density_g_per_ml = 0.3
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'coconut whip';

-- coconut yogurt: no FDC food; yogurts sit at ~1.03 (typical)
update ingredient set density_g_per_ml = 1.03
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'coconut yogurt';

-- plant butter: no FDC food; label (Miyoko's/Country Crock plant) tbsp = 14 g -> 0.95, matching dairy butter
update ingredient set density_g_per_ml = 0.95
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'plant butter';

-- chili crisp: no FDC food; oil plus settled solids — label (Fly By Jing/Lao Gan Ma) tbsp ~= 14 g -> 0.95
update ingredient set density_g_per_ml = 0.95
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'chili crisp';

-- bouillon paste: no FDC food; label (Better Than Bouillon) tsp = 6 g -> 1.22
update ingredient set density_g_per_ml = 1.22
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'bouillon paste';

-- liquid amino: no FDC food; soy-sauce family (FDC tamari cup 255 g -> 1.08)
update ingredient set density_g_per_ml = 1.08
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'liquid amino';

-- liquid smoke: an aqueous smoke condensate (dash default, but the curated tsp entry needs the volume bridge); water-like (typical)
update ingredient set density_g_per_ml = 1
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'liquid smoke';

-- vegan worcestershire sauce: no FDC vegan food; FDC worcestershire (170063) cup is 275 g -> 1.16 — the vegan recipe differs only in omitting anchovy
update ingredient set density_g_per_ml = 1.16
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'vegan worcestershire sauce';

-- oregano fresh: no FDC food for fresh oregano; fresh-herb leaves run ~0.7-0.8 g/tsp (FDC fresh thyme family) -> 0.15 (typical)
update ingredient set density_g_per_ml = 0.15
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'oregano fresh';

-- tender green: a salad-greens slot; its members bracket it (spinach 0.127, arugula 0.085) -> 0.1 (typical)
update ingredient set density_g_per_ml = 0.1
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'tender green';

-- vegan parmesan: no FDC vegan food; grated parmesan runs ~100 g/cup -> 0.42 (borrowed family value)
update ingredient set density_g_per_ml = 0.42
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'vegan parmesan';

-- chickpea canned: audit suggested ~1.02 (undrained can) but the linked FDC 173800 is DRAINED SOLIDS — the macro basis; a cup of drained chickpeas is ~164 g -> 0.69 (recorded disagreement)
update ingredient set density_g_per_ml = 0.69
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'chickpea canned';

-- pinto bean canned: linked FDC 174286 is drained solids; a cup of drained pinto beans is ~171 g -> 0.72 (audit's ~1.05 was the undrained can — recorded disagreement)
update ingredient set density_g_per_ml = 0.72
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'pinto bean canned';

-- dark red kidney bean canned: linked FDC 174285 is drained solids; a cup of drained kidney beans is ~175 g -> 0.74 (audit's ~1.05 was the undrained can — recorded disagreement)
update ingredient set density_g_per_ml = 0.74
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'dark red kidney bean canned';

-- light red kidney bean canned: linked FDC 174285 is drained solids; a cup of drained kidney beans is ~175 g -> 0.74 (recorded disagreement, as dark red)
update ingredient set density_g_per_ml = 0.74
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'light red kidney bean canned';

-- shiitake mushroom: FDC 169242 has no volume portion; borrowed from the mushroom family (maitake's diced cup 70 g -> 0.30) for sliced-cup entry
update ingredient set density_g_per_ml = 0.3
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'shiitake mushroom';

-- black bean canned: round-2 ruling (a): drained-solids cup (~171 g), matching the borrowed drained macros/can
update ingredient set density_g_per_ml = 0.72
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'black bean canned';

-- black eyed pea canned: round-2 ruling (a): drained-solids cup (~171 g), matching the borrowed drained macros/can
update ingredient set density_g_per_ml = 0.72
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'black eyed pea canned';

-- cannellini bean canned: round-2 ruling (a): drained-solids cup (~171 g), matching the borrowed drained macros/can
update ingredient set density_g_per_ml = 0.72
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cannellini bean canned';

-- great northern bean canned: round-2 ruling (a): drained-solids cup (~171 g), matching the borrowed drained macros/can
update ingredient set density_g_per_ml = 0.72
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'great northern bean canned';

-- navy bean canned: round-2 ruling (a): drained-solids cup (~171 g), matching the borrowed drained macros/can
update ingredient set density_g_per_ml = 0.72
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'navy bean canned';

-- vegetable broth: round-2 audit: FDC 171583's 221 g cup (0.934) is the same low-cup quirk fixed for almond milk — a clear broth is water-like
update ingredient set density_g_per_ml = 1
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'vegetable broth';

-- crispy shallot: round-2 audit: tbsp default needs the bridge (R1) — a spoonful of fried shallot bits is ~5 g (label typical)
update ingredient set density_g_per_ml = 0.34
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'crispy shallot';

-- Density fallback: FAO/INFOODS Density Database v2.0 (2012), via the reviewed
-- fao_density_links.jsonl map. Fills ONLY rows the FDC volume-portion
-- derivation and the curation overrides above both left null; the
-- null guard on each statement is what enforces that. 12 fills,
-- 30 tail rows audited and honestly left density-less.

-- burger bun <- FAO "Bread, roll, soft" [FNDDS 4.1; Cereal and cereal products]:
--   a burger bun IS a soft bread roll — FNDDS 4.1's 0.18 is the whole-roll packing density, not a crumb density
update ingredient set
  density_g_per_ml = 0.18,
  source = case when source is null or source = 'seed'
    then 'fao_infoods_v2:Bread, roll, soft'
    else source || ' + fao_infoods_v2:Bread, roll, soft' end
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'burger bun'
  and density_g_per_ml is null;

-- gold potato <- FAO "Potato, english, raw" [KEN; Tubers and products]:
--   KEN's 'english potato' is the ordinary white/yellow table potato — the same food. Foundation 2346403 has no volume portion
update ingredient set
  density_g_per_ml = 0.59,
  source = case when source is null or source = 'seed'
    then 'fao_infoods_v2:Potato, english, raw'
    else source || ' + fao_infoods_v2:Potato, english, raw' end
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'gold potato'
  and density_g_per_ml is null;

-- green olive <- FAO "Olives, green, with stone" [RC; Vegetables]:
--   RC's row is exactly this food in its jarred form, stone in. FDC 169096 has only mass portions
update ingredient set
  density_g_per_ml = 0.65,
  source = case when source is null or source = 'seed'
    then 'fao_infoods_v2:Olives, green, with stone'
    else source || ' + fao_infoods_v2:Olives, green, with stone' end
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'green olive'
  and density_g_per_ml is null;

-- multigrain bread <- FAO "Bread" [FNDDS 4.1; Cereal and cereal products]:
--   FNDDS 4.1's generic sliced-loaf row (0.29). A multigrain crumb is slightly denser, but FAO publishes to two decimals and the generic loaf is the honest figure at that resolution
update ingredient set
  density_g_per_ml = 0.29,
  source = case when source is null or source = 'seed'
    then 'fao_infoods_v2:Bread'
    else source || ' + fao_infoods_v2:Bread' end
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'multigrain bread'
  and density_g_per_ml is null;

-- poblano pepper <- FAO "Chili, green" [KEN; Vegetables]:
--   a poblano IS a mild fresh green chilli; KEN's 0.5 matches the sweet-pepper row (0.51) it sits beside, which is the cross-check
update ingredient set
  density_g_per_ml = 0.5,
  source = case when source is null or source = 'seed'
    then 'fao_infoods_v2:Chili, green'
    else source || ' + fao_infoods_v2:Chili, green' end
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'poblano pepper'
  and density_g_per_ml is null;

-- red onion <- FAO "Onions, raw, cubed" [RC; Vegetables]:
--   RC's fresh raw cubed onion (0.55) is the form a cup of chopped onion takes; bulb colour does not change packing density. FDC 790577 carries no volume portion, which is why the row is bare
update ingredient set
  density_g_per_ml = 0.55,
  source = case when source is null or source = 'seed'
    then 'fao_infoods_v2:Onions, raw, cubed'
    else source || ' + fao_infoods_v2:Onions, raw, cubed' end
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'red onion'
  and density_g_per_ml is null;

-- soft sandwich bread <- FAO "Bread, white, sliced, prepacked" [FNDDS 4.1; Cereal and cereal products]:
--   a soft prepacked sliced white loaf — the same food FNDDS describes (it already shares FDC 325871 with White Bread)
update ingredient set
  density_g_per_ml = 0.29,
  source = case when source is null or source = 'seed'
    then 'fao_infoods_v2:Bread, white, sliced, prepacked'
    else source || ' + fao_infoods_v2:Bread, white, sliced, prepacked' end
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'soft sandwich bread'
  and density_g_per_ml is null;

-- sprouted multigrain bread <- FAO "Bread" [FNDDS 4.1; Cereal and cereal products]:
--   as multigrain bread. Ezekiel-style sprouted loaves run denser than the generic 0.29; this is FAO's floor for the form, and a user edit is the place for the brand's own number
update ingredient set
  density_g_per_ml = 0.29,
  source = case when source is null or source = 'seed'
    then 'fao_infoods_v2:Bread'
    else source || ' + fao_infoods_v2:Bread' end
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'sprouted multigrain bread'
  and density_g_per_ml is null;

-- tatsoi <- FAO "Salad, green, leaves, raw" [RC; Vegetables]:
--   tatsoi is sold and eaten as a raw salad leaf, so RC's raw-salad-leaf row is its form. Lands at 0.06 against the curated kale 0.089 / arugula 0.085 — the light end of the same honest band
update ingredient set
  density_g_per_ml = 0.06,
  source = case when source is null or source = 'seed'
    then 'fao_infoods_v2:Salad, green, leaves, raw'
    else source || ' + fao_infoods_v2:Salad, green, leaves, raw' end
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'tatsoi'
  and density_g_per_ml is null;

-- wheat bread whole <- FAO "Bread" [FNDDS 4.1; Cereal and cereal products]:
--   as multigrain bread: FAO has no wholemeal row, and the generic sliced loaf is the same form
update ingredient set
  density_g_per_ml = 0.29,
  source = case when source is null or source = 'seed'
    then 'fao_infoods_v2:Bread'
    else source || ' + fao_infoods_v2:Bread' end
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'wheat bread whole'
  and density_g_per_ml is null;

-- white bread <- FAO "Bread, white, sliced, prepacked" [FNDDS 4.1; Cereal and cereal products]:
--   FNDDS 4.1's row is precisely this food; a density is what makes '2 cups cubed bread' computable
update ingredient set
  density_g_per_ml = 0.29,
  source = case when source is null or source = 'seed'
    then 'fao_infoods_v2:Bread, white, sliced, prepacked'
    else source || ' + fao_infoods_v2:Bread, white, sliced, prepacked' end
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'white bread'
  and density_g_per_ml is null;

-- yellow bell pepper <- FAO "Sweet pepper, raw, cubes" [RC; Vegetables]:
--   RC's raw diced sweet pepper (0.51) is exactly this food in exactly the form a cup of it is cut to; FAO does not distinguish the colour
update ingredient set
  density_g_per_ml = 0.51,
  source = case when source is null or source = 'seed'
    then 'fao_infoods_v2:Sweet pepper, raw, cubes'
    else source || ' + fao_infoods_v2:Sweet pepper, raw, cubes' end
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'yellow bell pepper'
  and density_g_per_ml is null;

-- Re-materialize allowed_units with post-prefill (and post-override)
-- densities: the insert trigger ran before seed_prefill landed them,
-- so density-unlocked families are missing until this refresh.
update ingredient set allowed_units = default_allowed_units(
  default_unit, macros_basis, density_g_per_ml, category)
where household_id = '00000000-0000-0000-0000-0000000000aa' and deleted_at is null;

-- RETIRED 2026-08-31 (migration 0014 / ADR-0009): the produce volume
-- leg used to live here as a category-gated patch — 49 piece-default
-- produce rows given cup/tbsp/ml explicitly because ADR-0008's density
-- leg fired only for mass/volume defaults ("a density can't describe
-- a piece"), so "1 cup diced mango" failed on import even though the
-- row had carried an honest density all along. ADR-0009 amended the
-- rule instead: a density unlocks the other mass/volume family
-- whatever the default unit's family, so the refresh above now emits
-- those admissions on its own. One source of the fact; the safety net
-- is a pgTAP assertion (supabase/tests/unit_admission.sql), not a
-- second stored copy of the rule.

-- coconut milk: count-default (sold by the can) but recipes also speak cups/tbsp of it, and its density makes volume honest
update ingredient set allowed_units = allowed_units || '["cup"]'::jsonb
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'coconut milk' and not allowed_units ? 'cup';

update ingredient set allowed_units = allowed_units || '["tbsp"]'::jsonb
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'coconut milk' and not allowed_units ? 'tbsp';

update ingredient set allowed_units = allowed_units || '["ml"]'::jsonb
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'coconut milk' and not allowed_units ? 'ml';

-- liquid smoke: dash-default, but the recipes that measure it say 1/2 tsp — g alone is no way to say that
update ingredient set allowed_units = allowed_units || '["tsp"]'::jsonb
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'liquid smoke' and not allowed_units ? 'tsp';

-- allspice ground: pinch-default spice that recipes still spoon (1/2 tsp allspice)
update ingredient set allowed_units = allowed_units || '["tsp"]'::jsonb
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'allspice ground' and not allowed_units ? 'tsp';

-- clove ground: pinch-default spice that recipes still spoon
update ingredient set allowed_units = allowed_units || '["tsp"]'::jsonb
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'clove ground' and not allowed_units ? 'tsp';

-- nutmeg ground: pinch-default spice that recipes still spoon
update ingredient set allowed_units = allowed_units || '["tsp"]'::jsonb
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'nutmeg ground' and not allowed_units ? 'tsp';

-- hot sauce: condiment-class pantry row (the vocab has no condiment category); hot sauce is added to taste
update ingredient set allowed_units = allowed_units || '["to_taste"]'::jsonb
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'hot sauce' and not allowed_units ? 'to_taste';

-- sriracha: condiment-class pantry row; added to taste
update ingredient set allowed_units = allowed_units || '["to_taste"]'::jsonb
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'sriracha' and not allowed_units ? 'to_taste';

-- soy sauce: condiment-class pantry row; seasoned to taste
update ingredient set allowed_units = allowed_units || '["to_taste"]'::jsonb
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'soy sauce' and not allowed_units ? 'to_taste';

-- tamari: condiment-class pantry row; seasoned to taste
update ingredient set allowed_units = allowed_units || '["to_taste"]'::jsonb
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'tamari' and not allowed_units ? 'to_taste';

-- liquid amino: condiment-class pantry row; seasoned to taste
update ingredient set allowed_units = allowed_units || '["to_taste"]'::jsonb
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'liquid amino' and not allowed_units ? 'to_taste';

-- vegan worcestershire sauce: condiment-class pantry row; seasoned to taste
update ingredient set allowed_units = allowed_units || '["to_taste"]'::jsonb
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'vegan worcestershire sauce' and not allowed_units ? 'to_taste';

-- bay leaf: bay leaves are counted, never pinched — the category gate overreaches here
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'bay leaf';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'bay leaf';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'bay leaf';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'to_taste')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'bay leaf';

-- star anise: star anise pods are counted, never pinched
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'star anise';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'star anise';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'star anise';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'to_taste')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'star anise';

-- pasta: a spoon of dry pasta is senseless; the density leg keeps cup/ml
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'pasta';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'pasta';

-- spaghetti: a spoon of spaghetti is senseless
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'spaghetti';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'spaghetti';

-- pea frozen: frozen peas are poured by the cup, not spooned by the tsp
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'pea frozen';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'pea frozen';

-- brussel sprout: whole sprouts do not fit in spoons
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'brussel sprout';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'brussel sprout';

-- edamame frozen: pods/beans are cupped, not spooned
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'edamame frozen';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'edamame frozen';

-- green bean: whole beans do not fit in spoons
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'green bean';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'green bean';

-- green bean canned: whole beans do not fit in spoons
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'green bean canned';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'green bean canned';

-- okra: whole pods do not fit in spoons
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'okra';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'okra';

-- cremini mushroom: whole mushrooms do not fit in spoons
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cremini mushroom';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cremini mushroom';

-- enoki mushroom: whole mushrooms do not fit in spoons
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'enoki mushroom';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'enoki mushroom';

-- king oyster mushroom: whole mushrooms do not fit in spoons
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'king oyster mushroom';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'king oyster mushroom';

-- maitake mushroom: whole mushrooms do not fit in spoons
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'maitake mushroom';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'maitake mushroom';

-- oyster mushroom: whole mushrooms do not fit in spoons
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'oyster mushroom';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'oyster mushroom';

-- white mushroom: whole mushrooms do not fit in spoons
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'white mushroom';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'white mushroom';

-- tempeh: a slab food — cut or weighed, never spooned
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'tempeh';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'tempeh';

-- tomato canned whole: whole canned tomatoes are not spooned; cup/ml stay for the juice-packed pour
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'tomato canned whole';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'tomato canned whole';

-- baked bean: beans by the tbsp exist in salads; by the tsp they do not
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'baked bean';

-- black bean canned: beans by the tbsp exist; by the tsp they do not
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'black bean canned';

-- black eyed pea canned: beans by the tbsp exist; by the tsp they do not
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'black eyed pea canned';

-- cannellini bean canned: beans by the tbsp exist; by the tsp they do not
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cannellini bean canned';

-- great northern bean canned: beans by the tbsp exist; by the tsp they do not
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'great northern bean canned';

-- navy bean canned: beans by the tbsp exist; by the tsp they do not
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'navy bean canned';

-- olive oil: a pinch of a liquid is senseless; to_taste stays — olive oil finishes dishes
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'olive oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'olive oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'olive oil';

-- sesame oil toasted: a pinch of a liquid is senseless; to_taste stays — toasted sesame is a finishing oil
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'sesame oil toasted';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'sesame oil toasted';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'sesame oil toasted';

-- avocado oil: a cooking oil is measured, not pinched or seasoned to taste
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'avocado oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'avocado oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'avocado oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'to_taste')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'avocado oil';

-- sunflower oil: a cooking oil is measured, not pinched or seasoned to taste
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'sunflower oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'sunflower oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'sunflower oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'to_taste')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'sunflower oil';

-- coconut oil: a cooking oil is measured, not pinched or seasoned to taste
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'coconut oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'coconut oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'coconut oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'to_taste')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'coconut oil';

-- high heat oil: a cooking oil is measured, not pinched or seasoned to taste
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'high heat oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'high heat oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'high heat oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'to_taste')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'high heat oil';

-- canola oil: a cooking oil is measured, not pinched or seasoned to taste
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'canola oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'canola oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'canola oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'to_taste')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'canola oil';

-- corn oil: a cooking oil is measured, not pinched or seasoned to taste
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'corn oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'corn oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'corn oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'to_taste')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'corn oil';

-- peanut oil: a cooking oil is measured, not pinched or seasoned to taste
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'peanut oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'peanut oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'peanut oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'to_taste')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'peanut oil';

-- safflower oil: a cooking oil is measured, not pinched or seasoned to taste
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'safflower oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'safflower oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'safflower oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'to_taste')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'safflower oil';

-- vegetable oil: a cooking oil is measured, not pinched or seasoned to taste
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'vegetable oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'vegetable oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'vegetable oil';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'to_taste')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'vegetable oil';

-- plant butter: butter is measured in spoons/grams, not pinched
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'plant butter';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'plant butter';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'plant butter';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'to_taste')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'plant butter';

-- liquid smoke: the only non-spice row the imprecise tail reaches (dash-default): a handful of a liquid is senseless, same as the oils — dash/to_taste stay, they are how it is actually dosed
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'liquid smoke';

-- cabbage: the R2 weight default unlocked the volume family; cups of shredded cabbage are real, spoons are not
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cabbage';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cabbage';

-- romaine lettuce: cups of chopped romaine are real, spoons are not
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'romaine lettuce';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'romaine lettuce';

-- iceberg lettuce: cups of shredded iceberg are real, spoons are not
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'iceberg lettuce';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'iceberg lettuce';

-- red leaf lettuce: cups of torn leaves are real, spoons are not
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'red leaf lettuce';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'red leaf lettuce';

-- cantaloupe: cups of cubed melon are real, spoons are not
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cantaloupe';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cantaloupe';

-- pineapple: cups of pineapple chunks are real, spoons are not
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'pineapple';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'tbsp')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'pineapple';

-- cinnamon stick: quills are counted, never pinched — the category gate overreaches here (bay-leaf precedent)
update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'pinch')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cinnamon stick';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'dash')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cinnamon stick';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'handful')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cinnamon stick';

update ingredient set allowed_units = (select coalesce(jsonb_agg(e), '[]'::jsonb)
   from jsonb_array_elements_text(allowed_units) e
   where e <> 'to_taste')
where household_id = '00000000-0000-0000-0000-0000000000aa' and match_text = 'cinnamon stick';

-- R1 invariant (Simon, 2026-08-29): a volume default_unit REQUIRES a
-- density — a volume line on a density-less per-g ingredient can never
-- compute macros, so the class must not silently return. Fill an honest
-- density (FDC / label / typical, tagged) or flip the default to a
-- weight, always via the pipeline inputs.
do $$
declare violators text;
begin
  select string_agg(canonical_name || ' (' || default_unit || ')', ', ')
    into violators
  from ingredient
  where household_id = '00000000-0000-0000-0000-0000000000aa' and deleted_at is null
    and default_unit in ('ml', 'l', 'tsp', 'tbsp', 'fl_oz', 'cup')
    and density_g_per_ml is null;
  if violators is not null then
    raise exception
      'seed_curation R1: volume-default rows with no density: %',
      violators;
  end if;

  -- R2: every stored density is a KITCHEN density. A number outside
  -- this band is a parse artifact or the wrong physical quantity (FAO
  -- publishes salt at 2.165 and bicarbonate at 2.2 — crystal densities,
  -- not what a spoonful weighs). Generation bounds the FAO fills; this
  -- bounds what actually landed, whatever the source.
  select string_agg(
           canonical_name || ' (' || density_g_per_ml || ')', ', ')
    into violators
  from ingredient
  where household_id = '00000000-0000-0000-0000-0000000000aa' and deleted_at is null
    and density_g_per_ml is not null
    and density_g_per_ml not between 0.03 and 2;
  if violators is not null then
    raise exception
      'seed_curation R2: densities outside 0.03-2 g/ml: %',
      violators;
  end if;

  raise notice 'seed_curation: allowed_units refreshed; 11 macro + 59 density + 55 allowed-unit overrides + 12 FAO density fills; R1 (volume default => density) and R2 (kitchen density band) hold';
end $$;

commit;
