-- seed_curation.sql — GENERATED by scripts/gen_seed.ts from
-- curation_overrides.jsonl. Do not edit by hand; edit the overrides
-- (with reasons) and regenerate (deno task gen-seed).
--
-- Runs LAST: refreshes the template vocab's materialized allowed_units
-- now that every density source has run, then applies the audited
-- curation overrides (plan 0013).

begin;

-- Re-materialize allowed_units with post-prefill (and post-override)
-- densities: the insert trigger ran before seed_prefill landed them,
-- so density-unlocked families are missing until this refresh.
update ingredient set allowed_units = default_allowed_units(
  default_unit, macros_basis, density_g_per_ml, category)
where household_id = '00000000-0000-0000-0000-0000000000aa' and deleted_at is null;

do $$ begin
  raise notice 'seed_curation: allowed_units refreshed; 0 density + 0 allowed-unit overrides';
end $$;

commit;
