// Builds the usda_food reference seed from USDA FoodData Central CSV bundles
// (Foundation Foods + SR Legacy, CC0). Server-side reference only — never synced,
// never matched against at import (ADR-0005). See seed_usda.md for how to fetch
// the data (it is NOT committed — ~40MB of CSV; only the compact seed is).
//
//   deno run --allow-read --allow-write gen_usda.ts <dataset_dir> [<dataset_dir>...]
//
// Emits supabase/seed_usda.sql (a COPY block, ~8k rows). Keeps only the four
// macros (per 100 g) and a density derived from a volume food_portion. match_text
// is the shared §7 normalizer over the description, so the same normalizer the
// household vocab and cascade use also indexes the reference.

import { parse } from "@std/csv/parse";
import { normalize } from "../../functions/_shared/normalize.ts";

// FDC nutrient ids for the macros we keep. Fiber has two encodings: 1079 (total
// dietary) and 2033 (AOAC 2011.25, used by some Foundation foods) — prefer 1079.
const KCAL = "1008", PROTEIN = "1003", CARB = "1005", FAT = "1004";
const FIBER = "1079", FIBER_AOAC = "2033";
// Only these data_types are real foods to seed (Foundation ships sample rows too).
const FOODS = new Set(["foundation_food", "sr_legacy_food"]);

// Volume measure units → millilitres, for deriving density (g / ml).
const ML_PER: Record<string, number> = {
  cup: 236.588,
  tablespoon: 14.7868,
  teaspoon: 4.92892,
  "fl oz": 29.5735,
  "fluid ounce": 29.5735,
  liter: 1000,
  milliliter: 1,
  pint: 473.176,
  quart: 946.353,
  gallon: 3785.41,
};

interface Row {
  fdc_id: string;
  description: string;
  category: string | null;
  density: number | null;
  macros: Record<string, number>;
}

function readCsv(path: string): Record<string, string>[] {
  return parse(Deno.readTextFileSync(path), { skipFirstRow: true });
}

function loadDataset(dir: string, rows: Map<string, Row>): void {
  const categories = new Map<string, string>();
  for (const c of readCsv(`${dir}/food_category.csv`)) {
    categories.set(c.id, c.description);
  }
  const units = new Map<string, string>();
  for (const u of readCsv(`${dir}/measure_unit.csv`)) units.set(u.id, u.name);

  for (const f of readCsv(`${dir}/food.csv`)) {
    if (!FOODS.has(f.data_type)) continue;
    rows.set(f.fdc_id, {
      fdc_id: f.fdc_id,
      description: f.description,
      category: categories.get(f.food_category_id) ?? null,
      density: null,
      macros: {},
    });
  }

  // Macros: food_nutrient.csv is large; hand-split (its numeric/id fields carry
  // no embedded commas) and keep only the four nutrients for foods we loaded.
  const KEEP: Record<string, string> = {
    [KCAL]: "kcal",
    [PROTEIN]: "protein",
    [CARB]: "carb",
    [FAT]: "fat",
    [FIBER]: "fiber",
    [FIBER_AOAC]: "fiber_aoac",
  };
  const nutrientText = Deno.readTextFileSync(`${dir}/food_nutrient.csv`);
  let first = true;
  for (const line of nutrientText.split("\n")) {
    if (first) {
      first = false;
      continue;
    }
    if (!line) continue;
    const c = line.slice(1, -1).split('","'); // strip outer quotes, split
    const key = KEEP[c[2]];
    if (!key) continue;
    const row = rows.get(c[1]);
    if (row) row.macros[key] = Number(c[3]);
  }

  // Density from the first usable volume portion.
  for (const p of readCsv(`${dir}/food_portion.csv`)) {
    const row = rows.get(p.fdc_id);
    if (!row || row.density !== null) continue;
    const ml = ML_PER[units.get(p.measure_unit_id) ?? ""];
    const amount = Number(p.amount), grams = Number(p.gram_weight);
    if (ml && amount > 0 && grams > 0) row.density = grams / (amount * ml);
  }
}

function main(): void {
  const dirs = Deno.args;
  if (dirs.length === 0) {
    console.error("usage: gen_usda.ts <dataset_dir> [<dataset_dir>...]");
    Deno.exit(1);
  }
  // Foundation first so it wins on any fdc_id overlap (it won't, but for macros
  // quality the earlier dataset is preferred — pass Foundation before SR Legacy).
  const rows = new Map<string, Row>();
  for (const dir of dirs) loadDataset(dir, rows);

  // Batched multi-row INSERTs — the Supabase CLI seeder can't stream COPY.
  const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
  const cols =
    "(fdc_id, description, category, density_g_per_ml, macros, match_text)";
  const out: string[] = [
    "-- seed_usda.sql — GENERATED by scripts/gen_usda.ts (USDA FDC, CC0).",
    "-- Server-side reference only: never synced, never matched at import (ADR-0005).",
  ];
  const all = [...rows.values()];
  let withDensity = 0, withFiber = 0;
  const BATCH = 500;
  for (let i = 0; i < all.length; i += BATCH) {
    const tuples = all.slice(i, i + BATCH).map((r) => {
      if (r.density !== null) withDensity++;
      const m = r.macros;
      if (m.fiber === undefined && m.fiber_aoac !== undefined) {
        m.fiber = m.fiber_aoac;
      }
      delete m.fiber_aoac;
      if (m.fiber !== undefined) withFiber++;
      return "(" + [
        r.fdc_id,
        q(r.description),
        r.category === null ? "null" : q(r.category),
        r.density === null ? "null" : r.density.toFixed(4),
        `${q(JSON.stringify(m))}::jsonb`,
        q(normalize(r.description)),
      ].join(", ") + ")";
    });
    out.push(`insert into usda_food ${cols} values`, tuples.join(",\n") + ";");
  }
  out.push("");

  const target = new URL("../../seed_usda.sql", import.meta.url).pathname;
  Deno.writeTextFileSync(target, out.join("\n"));
  console.log(
    `wrote ${target}\n  ${rows.size} foods (${withDensity} density, ${withFiber} fiber)`,
  );
}

if (import.meta.main) main();
