// Generates supabase/seed.sql from the arbiter's curated vocabulary
// (out/seed_vocab.jsonl). The LLM arbiter makes the ingredient judgments; this
// step is deterministic — it computes each row's match_text with the SHARED §7
// normalizer (so stored match_text is symmetric with the runtime cascade) and
// emits plain SQL. Run: deno task gen-seed
//
// Everything seeds as status='stub' (no density/macros yet — honest numbers).

import { normalize } from "../../functions/_shared/normalize.ts";
import { readOverrides } from "./overrides.ts";

// A fixed household so re-generating is stable and the seed is idempotent under
// `supabase db reset`.
const HOUSEHOLD_ID = "00000000-0000-0000-0000-0000000000aa";
const HOUSEHOLD_NAME = "Home";

// Valid units.dart ids (default_unit must be one of these).
const UNIT_IDS = new Set([
  "g",
  "kg",
  "mg",
  "oz",
  "lb",
  "ml",
  "l",
  "tsp",
  "tbsp",
  "fl_oz",
  "cup",
  "piece",
  "pinch",
  "dash",
  "to_taste",
]);

interface VocabRow {
  canonical_name: string;
  category?: string;
  default_unit?: string;
  aliases?: string[];
  source_examples?: string[];
  notes?: string;
}

const sqlStr = (s: string) => `'${s.replace(/'/g, "''")}'`;

function main(): void {
  const dir = new URL(".", import.meta.url).pathname;
  // Optional overrides for testing: gen_seed.ts [inputJsonl] [outputSql].
  // Default input is the committed curated vocab (LLM+human judgment — tracked,
  // unlike the regenerable raw mining outputs in out/).
  const inputPath = Deno.args[0] ?? `${dir}../vocab.jsonl`;
  const outputPath = Deno.args[1] ?? `${dir}../../seed.sql`;
  const rows: VocabRow[] = Deno.readTextFileSync(inputPath)
    .split("\n").map((l) => l.trim()).filter(Boolean).map((l) => JSON.parse(l));

  // Validate + compute match_text. Collisions would break the alias join, so
  // fail loudly rather than emit a broken seed.
  const byMatch = new Map<string, string>();
  const problems: string[] = [];
  const ingredients = rows.map((r) => {
    const match = normalize(r.canonical_name);
    if (!match) problems.push(`empty match_text for ${r.canonical_name}`);
    if (byMatch.has(match)) {
      problems.push(
        `match_text "${match}" collides: ${
          byMatch.get(match)
        } vs ${r.canonical_name}`,
      );
    }
    byMatch.set(match, r.canonical_name);
    if (r.default_unit && !UNIT_IDS.has(r.default_unit)) {
      problems.push(
        `bad default_unit "${r.default_unit}" on ${r.canonical_name}`,
      );
    }
    return { ...r, match };
  });
  if (problems.length) {
    console.error(
      "seed vocab problems:\n" + problems.map((p) => "  " + p).join("\n"),
    );
    Deno.exit(1);
  }

  // Alias rows, deduped and joined to their ingredient by the ingredient's
  // match_text. Skip an alias whose normalized form equals the canonical's (the
  // canonical already matches it) or collides with a different ingredient.
  const aliasRows: string[] = [];
  for (const ing of ingredients) {
    const seen = new Set([ing.match]);
    for (const alias of ing.aliases ?? []) {
      const am = normalize(alias);
      if (!am || seen.has(am)) continue;
      seen.add(am);
      aliasRows.push(
        `  (${sqlStr(ing.match)}, ${sqlStr(alias)}, ${sqlStr(am)})`,
      );
    }
  }

  const out: string[] = [];
  out.push(
    "-- seed.sql — GENERATED by scripts/gen_seed.ts from scripts/out/seed_vocab.jsonl.",
    "-- Do not edit by hand; edit the vocab and regenerate (deno task gen-seed).",
    "-- Initial household + starter ingredient vocabulary. All status='stub' —",
    "-- density/macros are filled later (honest numbers).",
    "",
    "begin;",
    "",
    "-- is_template (0008): \"Home\" is the member-less vocab template new",
    "-- households clone from at onboarding; template households are never",
    "-- joinable.",
    `insert into household (id, name, is_template)`,
    `values (${sqlStr(HOUSEHOLD_ID)}, ${sqlStr(HOUSEHOLD_NAME)}, true)`,
    "on conflict (id) do update set is_template = true;",
    "",
    "insert into ingredient",
    "  (household_id, canonical_name, category, default_unit, status, source, match_text)",
    "values",
  );
  out.push(
    ingredients.map((ing) =>
      "  (" + [
        sqlStr(HOUSEHOLD_ID),
        sqlStr(ing.canonical_name),
        ing.category ? sqlStr(ing.category) : "null",
        sqlStr(ing.default_unit ?? "piece"),
        "'stub'",
        "'seed'",
        sqlStr(ing.match),
      ].join(", ") + ")"
    ).join(",\n") + ";",
  );

  if (aliasRows.length) {
    out.push(
      "",
      "insert into ingredient_alias",
      "  (household_id, ingredient_id, alias_text, match_text, source)",
      `select ${
        sqlStr(HOUSEHOLD_ID)
      }, i.id, a.alias_text, a.alias_match, 'seed'`,
      "from ingredient i",
      "join (values",
      aliasRows.join(",\n"),
      ") as a(ing_match, alias_text, alias_match) on i.match_text = a.ing_match",
      `where i.household_id = ${sqlStr(HOUSEHOLD_ID)};`,
    );
  }
  out.push("", "commit;", "");

  Deno.writeTextFileSync(outputPath, out.join("\n"));
  console.log(
    `wrote ${outputPath}\n  ${ingredients.length} ingredients, ${aliasRows.length} aliases`,
  );

  writePrefill(dir);
  writeCuration(dir);
}

// seed_prefill.sql — fills macros/density from usda_food for the ingredients
// linked to a USDA fdc_id (auto trigram matches + arbiter picks, in
// usda_links.jsonl). Runs AFTER seed_usda.sql (see config.toml sql_paths).
function writePrefill(dir: string): void {
  const linksPath = `${dir}../usda_links.jsonl`;
  let text: string;
  try {
    text = Deno.readTextFileSync(linksPath);
  } catch {
    return; // no links yet — prefill is optional
  }
  const links = text.split("\n").map((l) => l.trim()).filter(Boolean)
    .map((l) => JSON.parse(l) as { match_text: string; fdc_id: number });
  if (links.length === 0) return;

  const rows = links.map((l) => `  (${sqlStr(l.match_text)}, ${l.fdc_id})`);
  const sql = [
    "-- seed_prefill.sql — GENERATED by scripts/gen_seed.ts from usda_links.jsonl.",
    "-- Fills macros/density from the usda_food reference for linked ingredients.",
    "-- Runs after seed_usda.sql. status → 'complete' once macros are present.",
    "",
    "update ingredient i set",
    "  -- only overwrite macros when the reference actually has them",
    "  macros = case when u.macros ? 'kcal' then u.macros else i.macros end,",
    "  density_g_per_ml = coalesce(u.density_g_per_ml, i.density_g_per_ml),",
    "  source = 'usda_fdc:' || u.fdc_id,",
    "  status = case when u.macros ? 'kcal' then 'complete' else i.status end",
    "from (values",
    rows.join(",\n"),
    ") as m(match_text, fdc_id)",
    "join usda_food u on u.fdc_id = m.fdc_id",
    `where i.match_text = m.match_text and i.household_id = ${
      sqlStr(HOUSEHOLD_ID)
    };`,
    "",
  ];
  const target = `${dir}../../seed_prefill.sql`;
  Deno.writeTextFileSync(target, sql.join("\n"));
  console.log(`wrote ${target}\n  ${links.length} usda prefill links`);
}

// seed_curation.sql — the LAST seed step (config.toml sql_paths order):
//
//   1. refreshes the template vocab's materialized `allowed_units` from
//      `default_allowed_units()` (0012) — the insert-time trigger ran before
//      seed_prefill landed densities, so the density-unlocked family only
//      appears once every density source has run;
//   2. applies the committed curation overrides (curation_overrides.jsonl,
//      plan 0013): per-ingredient densities and allowed-unit adjustments a
//      human judged the rules wrong about, each with its reason emitted as a
//      SQL comment so the generated file stays auditable on its own.
//
// Measure overrides (drop/add) are gen_measures.ts's job — they change what
// seed_measures.sql emits rather than patching it afterwards.
function writeCuration(dir: string): void {
  const overrides = readOverrides(dir);
  const q = sqlStr;
  const sql: string[] = [
    "-- seed_curation.sql — GENERATED by scripts/gen_seed.ts from",
    "-- curation_overrides.jsonl. Do not edit by hand; edit the overrides",
    "-- (with reasons) and regenerate (deno task gen-seed).",
    "--",
    "-- Runs LAST: refreshes the template vocab's materialized allowed_units",
    "-- now that every density source has run, then applies the audited",
    "-- curation overrides (plan 0013).",
    "",
    "begin;",
    "",
  ];

  // Density overrides FIRST, so the allowed_units refresh below sees them.
  let densities = 0, unitTweaks = 0;
  for (const o of overrides) {
    if (o.kind === "density") {
      densities++;
      sql.push(
        `-- ${o.match_text}: ${o.reason}`,
        "update ingredient set density_g_per_ml = " +
          `${o.value === null ? "null" : o.value}`,
        `where household_id = ${q(HOUSEHOLD_ID)} and match_text = ${
          q(o.match_text)
        };`,
        "",
      );
    }
  }

  sql.push(
    "-- Re-materialize allowed_units with post-prefill (and post-override)",
    "-- densities: the insert trigger ran before seed_prefill landed them,",
    "-- so density-unlocked families are missing until this refresh.",
    "update ingredient set allowed_units = default_allowed_units(",
    "  default_unit, macros_basis, density_g_per_ml, category)",
    `where household_id = ${q(HOUSEHOLD_ID)} and deleted_at is null;`,
    "",
  );

  for (const o of overrides) {
    if (o.kind === "allowed_units") {
      unitTweaks++;
      sql.push(`-- ${o.match_text}: ${o.reason}`);
      if (o.set) {
        sql.push(
          "update ingredient set allowed_units = " +
            `${q(JSON.stringify(o.set))}::jsonb`,
          `where household_id = ${q(HOUSEHOLD_ID)} and match_text = ${
            q(o.match_text)
          };`,
          "",
        );
      } else {
        for (const u of o.add ?? []) {
          sql.push(
            "update ingredient set allowed_units = " +
              `allowed_units || ${q(JSON.stringify([u]))}::jsonb`,
            `where household_id = ${q(HOUSEHOLD_ID)} and match_text = ${
              q(o.match_text)
            } and not allowed_units ? ${q(u)};`,
            "",
          );
        }
        for (const u of o.remove ?? []) {
          sql.push(
            "update ingredient set allowed_units = " +
              "(select coalesce(jsonb_agg(e), '[]'::jsonb)",
            "   from jsonb_array_elements_text(allowed_units) e",
            `   where e <> ${q(u)})`,
            `where household_id = ${q(HOUSEHOLD_ID)} and match_text = ${
              q(o.match_text)
            };`,
            "",
          );
        }
      }
    }
  }

  sql.push(
    "do $$ begin",
    "  raise notice 'seed_curation: allowed_units refreshed; " +
      `${densities} density + ${unitTweaks} allowed-unit overrides';`,
    "end $$;",
    "",
    "commit;",
    "",
  );

  const target = `${dir}../../seed_curation.sql`;
  Deno.writeTextFileSync(target, sql.join("\n"));
  console.log(
    `wrote ${target}\n  ${densities} density + ${unitTweaks} allowed-unit overrides`,
  );
}

if (import.meta.main) main();
