// Runs the compiled share-page bundle the way the edge function will — a
// classic script evaluated into a Deno isolate with no document — checks the
// page it renders from the shared payload fixture, then writes the bundle's
// source as a string module for the function to serve.
//
//   deno run --allow-read --allow-write scripts/share_bundle_smoke.ts \
//     <bundle.js> <payload.json> <source.ts>

const [bundlePath, payloadPath, sourcePath] = Deno.args;
if (!bundlePath || !payloadPath || !sourcePath) {
  throw new Error(
    "usage: share_bundle_smoke.ts <bundle.js> <payload.json> <source.ts>",
  );
}

const source = await Deno.readTextFile(bundlePath);
// Indirect eval: the bundle is a classic script and sets a global.
(0, eval)(source);
const render = (globalThis as Record<string, unknown>).ansiSharePage;
if (typeof render !== "function") {
  throw new Error("the bundle did not export ansiSharePage");
}

const html = (render as (p: string, u: string, b: string) => string)(
  await Deno.readTextFile(payloadPath),
  "https://getansi.app/r/smoke",
  "/r/share_page.js",
);

const expected = [
  "<title>Miso Noodles &lt;spicy&gt;</title>",
  '<script type="application/ld+json">',
  '<span class="amt">2 blob (30 g)</span>',
  "<dt>kcal</dt><dd>346</dd>",
  'data-seconds="270"',
];
const missing = expected.filter((s) => !html.includes(s));
if (missing.length > 0) {
  throw new Error(`the rendered page is missing:\n  ${missing.join("\n  ")}`);
}
await Deno.writeTextFile(
  sourcePath,
  "// GENERATED by scripts/share_bundle.sh from share_page.js — do not edit.\n" +
    `export const SHARE_BUNDLE = ${JSON.stringify(source)};\n`,
);
console.log(
  `  ✓ share bundle renders the fixture (${
    Math.round(source.length / 1024)
  } KB, ${html.length} chars of HTML)`,
);
