/// The commit payload — PURE DART (invariant 2). Built client-side after the
/// user resolves every reconciliation line; handed to the import repository
/// which writes it through PowerSync.
///
/// **`recipe_line_item.ingredient_id` is NOT NULL** (0014): every `CommitLine`
/// carries either an existing `ingredientId` or a `stubKey` pointing at a
/// `CommitStub` the commit creates — there is no dangling line.
///
/// Step refs are still by **line index** here (`steps`); the repository assigns
/// `line_item_id`s in the flattened line order and remaps the refs on write
/// (§4.6). Stub ids and line ids are generated by the data layer (uuids +
/// timestamps live there), so this pure payload names stubs by a stable
/// `stubKey` instead of an id.
library;

import 'package:freezed_annotation/freezed_annotation.dart';

import 'reconciliation_payload.dart';

part 'commit_payload.freezed.dart';

/// A new stub ingredient the commit must create (`status='stub'`,
/// `source='import_stub'`). [key] is the coalescing handle — identical no-match
/// lines share one stub (0014's within-import dedupe).
@freezed
abstract class CommitStub with _$CommitStub {
  const factory CommitStub({required String key, required String name}) =
      _CommitStub;
}

/// A resolved line. Exactly one of [ingredientId] / [stubKey] is set.
@freezed
abstract class CommitLine with _$CommitLine {
  const factory CommitLine({
    /// The flattened line index — its position in the commit's line order and
    /// the value step tokens ref before the remap.
    required int lineIndex,
    String? ingredientId,
    String? stubKey,
    double? quantity,
    String? unit,
    String? note,
  }) = _CommitLine;
}

@freezed
abstract class CommitGroup with _$CommitGroup {
  const factory CommitGroup({
    String? name,
    @Default(<CommitLine>[]) List<CommitLine> lines,
  }) = _CommitGroup;
}

/// A user correction to write back as an alias (`source='import_correction'`,
/// lane B's learning loop): the raw [aliasText] now points at [ingredientId].
@freezed
abstract class CommitCorrection with _$CommitCorrection {
  const factory CommitCorrection({
    required String ingredientId,
    required String aliasText,
  }) = _CommitCorrection;
}

@freezed
abstract class CommitPayload with _$CommitPayload {
  const factory CommitPayload({
    required String title,
    required double servingsBase,
    String? servingsRaw,
    int? cookTimeSeconds,
    int? totalTimeSeconds,
    @Default(<CommitGroup>[]) List<CommitGroup> groups,
    @Default(<CommitStub>[]) List<CommitStub> stubs,
    @Default(<Step>[]) List<Step> steps,
    @Default(<CommitCorrection>[]) List<CommitCorrection> corrections,
  }) = _CommitPayload;
}
